

services:

  backend:
    build: .

    container_name: edurag-backend

    ports:
      - "8000:8000"

    env_file:
      - .env.docker

    depends_on:
      - postgres

    volumes:
      - ./uploads:/app/uploads
      - ./vector_db:/app/vector_db

    restart: unless-stopped


  postgres:

    image: postgres:16

    container_name: edurag-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: edurag

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped


volumes:

  postgres_data: